baseURL: https://examplesite.com
title: WFC | Workforce Capital 
theme: somrat
paginate: '8'
summaryLength: '10'
disableLanguages: yes
googleAnalytics: ''
disqusShortname: ''
outputs:
  home: HTML
markup:
  goldmark:
    renderer:
      unsafe: yes
params:
  author: Badr
  description: Strategic Workforce Planning (SWP) | People Analytics
  favicon: images/favicon.png
  logo_dark: images/logo-dark.png
  logo_light: images/logo.png
  logo_width: 150px
  plugins:
    css:
      - link: plugins/bootstrap/bootstrap.min.css
      - link: https://fonts.googleapis.com/css?family=Rubik:300,400,500,700,900&display=swap
      - link: https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css
      - link: plugins/hover/hover.css
      - link: plugins/magnific-popup/magnific-popup.css
      - link: plugins/owl-carousel/owl.carousel.min.css
      - link: plugins/owl-carousel/owl.theme.default.min.css
      - link: plugins/text-animation/text-animation.css
    js:
      - link: plugins/jQuery/jquery.min.js
      - link: plugins/bootstrap/bootstrap.min.js
      - link: plugins/wow.min.js
      - link: plugins/text-animation/text-animation.js
      - link: plugins/jquery.waypoints.min.js
      - link: plugins/shuffle/shuffle.min.js
      - link: plugins/magnific-popup/jquery.magnific-popup.min.js
      - link: plugins/owl-carousel/owl.carousel.min.js
  preloader:
    enable: yes
    preloader: images/preloader.gif
  social:
    - icon: fab fa-linkedin
      link: https://www.linkedin.com/in/badr-ait-ahmed-64a0631/
    - icon: fab fa-twitter
      link: https://twitter.com/BadrAitAhmed3
    - icon: fab fa-github
      link: https://github.com/WorkforceCapital
Languages:
  en:
    contentDir: content/english
    copyright: Copyright © 2021 Workforce Capital - All Rights Reserved. - Privacy Policy
    home: Home
    languageCode: en-us
    languageName: En
    menu:
      main:
        - name: ABOUT BADR
          pre: '#'
          url: about
          weight: 1
        - name: PEOPLE ANALYTICS
          pre: '#'
          url: peopleanalytics
          weight: 2
        - name: STRATEGIC WORKFORCE PLANNING
          pre: '#'
          url: swp
          weight: 3
        - name: CONTACT
          pre: '#'
          url: contact
          weight: 4
        - name: BLOG
          url: blog
          weight: 5
    weight: 1
  fr:
    contentDir: content/french
    copyright: Copyright © 2021 Workforce Capital - All Rights Reserved. - Privacy Policy 
    home: Accueil
    languageCode: fr-fr
    languageName: Fr
    menu:
      main:
        - name: ABOUT BADR
          pre: '#'
          url: about
          weight: 1
        - name: PEOPLE ANALYTICS
          pre: '#'
          url: peopleanalytics
          weight: 2
        - name: STRATEGIC WORKFORCE PLANNING
          pre: '#'
          url: swp
          weight: 3
        - name: CONTACT
          pre: '#'
          url: contact
          weight: 4
        - name: BLOG
          url: blog
          weight: 5
    weight: 2
